[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rustls = "0.23.20"
tokio-rustls = "0.26.1"
rustls-pemfile = "2.2.0"
